In [1]:
import numpy as np

In [49]:
# array creation and attributes

arr = np.arange(15)
print("arr value: \n" + str(arr) + "\n" + "arr.dtype: " + str(arr.dtype) + ", arr.itemsize: " + str(arr.itemsize) + "\n")

arr = np.reshape(arr, (3, 5))
print("reshaped arr: \n" + str(arr) + "\n" + "arr.dim: " + str(arr.ndim) + ", arr.shape: " + str(arr.shape) + "\n")

zeros_arr = np.zeros((2,3))
print("zeros_arr: \n" + str(zeros_arr) + "\n" + "zeros_arr.dtype: " + str(zeros_arr.dtype) + "\n")

ones_arr = np.ones((3, 4), dtype=np.int32)
print("ones_arr: \n" + str(ones_arr) + "\n" + "ones_arr.dtype: " + str(ones_arr.dtype) + "\n")

empty_arr = np.empty((2, 3))
print("empty_arr: \n" + str(empty_arr) + "\n" + "empty_arr.dtype: " + str(empty_arr.dtype))

arr value: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
arr.dtype: int32, arr.itemsize: 4

reshaped arr: 
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
arr.dim: 2, arr.shape: (3, 5)

zeros_arr: 
[[0. 0. 0.]
 [0. 0. 0.]]
zeros_arr.dtype: float64

ones_arr: 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
ones_arr.dtype: int32

empty_arr: 
[[2.12199579e-314 2.12199579e-314 2.12199579e-314]
 [2.12199579e-314 2.12199579e-314 2.12199579e-314]]
empty_arr.dtype: float64


In [48]:
# array arithmetic operations

# arithmetic operators on arrays apply elementwise

arr_a = np.array([1, 2, 3, 4])
arr_b = np.full(4, np.pi)
print("arr_a: " + str(arr_a))
print("arr_b: " + str(arr_b))

print("arr_a**2: " + str(arr_a**2))

print("arr_a * arr_b: " + str(arr_a * arr_b))

arr_a: [1 2 3 4]
arr_b: [3.14159265 3.14159265 3.14159265 3.14159265]
arr_a**2: [ 1  4  9 16]
arr_a * arr_b: [ 3.14159265  6.28318531  9.42477796 12.56637061]
